package pe.edu.unsch.entities;
// Generated 20-jul-2019 16:47:19 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Comprador generated by hbm2java
 */
public class Comprador implements java.io.Serializable {

	private Integer idcomprador;
	private Entrada entrada;
	private Pago pago;
	private String nombre;
	private String tipodoc;
	private String documento;
	private Date fechanacimiento;
	private String celular;
	private String departamento;
	private String provincia;
	private String distrito;
	private String correo;
	private String contra;

	public Comprador() {
	}

	public Comprador(Entrada entrada, Pago pago, String nombre, String tipodoc, String documento, Date fechanacimiento,
			String celular, String departamento, String provincia, String distrito, String correo, String contra) {
		this.entrada = entrada;
		this.pago = pago;
		this.nombre = nombre;
		this.tipodoc = tipodoc;
		this.documento = documento;
		this.fechanacimiento = fechanacimiento;
		this.celular = celular;
		this.departamento = departamento;
		this.provincia = provincia;
		this.distrito = distrito;
		this.correo = correo;
		this.contra = contra;
	}

	public Integer getIdcomprador() {
		return this.idcomprador;
	}

	public void setIdcomprador(Integer idcomprador) {
		this.idcomprador = idcomprador;
	}

	public Entrada getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Entrada entrada) {
		this.entrada = entrada;
	}

	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipodoc() {
		return this.tipodoc;
	}

	public void setTipodoc(String tipodoc) {
		this.tipodoc = tipodoc;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContra() {
		return this.contra;
	}

	public void setContra(String contra) {
		this.contra = contra;
	}

}
