package pe.edu.unsch.entities;
// Generated 20-jul-2019 16:47:19 by Hibernate Tools 5.3.0.Beta2

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private Integer idcuenta;
	private Rol rol;
	private String nombre;
	private String dni;
	private String correo;
	private String usuario;
	private String contra;

	public Cuenta() {
	}

	public Cuenta(Rol rol, String nombre, String dni, String correo, String usuario, String contra) {
		this.rol = rol;
		this.nombre = nombre;
		this.dni = dni;
		this.correo = correo;
		this.usuario = usuario;
		this.contra = contra;
	}

	public Integer getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(Integer idcuenta) {
		this.idcuenta = idcuenta;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContra() {
		return this.contra;
	}

	public void setContra(String contra) {
		this.contra = contra;
	}

}
