package pe.edu.unsch.entities;
// Generated 08-jul-2019 21:50:23 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Entrada generated by hbm2java
 */
public class Entrada implements java.io.Serializable {

	private Integer identrada;
	private String ubicacion;
	private long precio;
	private int cantidad;
	private String imagen;
	private Set compradors = new HashSet(0);

	public Entrada() {
	}

	public Entrada(String ubicacion, long precio, int cantidad, String imagen) {
		this.ubicacion = ubicacion;
		this.precio = precio;
		this.cantidad = cantidad;
		this.imagen = imagen;
	}

	public Entrada(String ubicacion, long precio, int cantidad, String imagen, Set compradors) {
		this.ubicacion = ubicacion;
		this.precio = precio;
		this.cantidad = cantidad;
		this.imagen = imagen;
		this.compradors = compradors;
	}

	public Integer getIdentrada() {
		return this.identrada;
	}

	public void setIdentrada(Integer identrada) {
		this.identrada = identrada;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public long getPrecio() {
		return this.precio;
	}

	public void setPrecio(long precio) {
		this.precio = precio;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set getCompradors() {
		return this.compradors;
	}

	public void setCompradors(Set compradors) {
		this.compradors = compradors;
	}

}
