package pe.edu.unsch.entities;
// Generated 08-jul-2019 21:50:23 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private int idrol;
	private String nombre;
	private Set cuentas = new HashSet(0);

	public Rol() {
	}

	public Rol(int idrol, String nombre) {
		this.idrol = idrol;
		this.nombre = nombre;
	}

	public Rol(int idrol, String nombre, Set cuentas) {
		this.idrol = idrol;
		this.nombre = nombre;
		this.cuentas = cuentas;
	}

	public int getIdrol() {
		return this.idrol;
	}

	public void setIdrol(int idrol) {
		this.idrol = idrol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
